language: php
php:
- 5.3
- 5.4
env:
  global:
  - TEST_3SCALE_APP_IDS=4d4b20b9 TEST_3SCALE_APP_KEYS=ecce202ecc2eb8dc7a499c34a34d5987
  - secure: "dibylTYaUYDf9OIVpGPma+BKc/QZiSaMoY7ISNv2TQVQefhDWB/jn7/8VBVCkEgdCJt3vZu7YVrjZ5RcHrI1SshC2v4FtHX85pf8++6OHcuNv1E8sCigGclF2L7l2kYIxPyrbbQGLp+TDtAXfPFRae4fhOkBebRE9aX9QJayAOE="
  - secure: "myAM1Jeqrm2AuOiz96g/3KgQtqAxdWNn/0JuTGyKU2bdORtTthrfWZ7L+Sx6NP1e/GsioJ9iuqp0Q4aEvoJ6JtQLJhAXeRSovnuNRvaVnPqAsI/E2530laQOuGw8qgVLr7Kq1BkfoIF2Hc7J74yu7+Tyog+uSA+hpIyadHbFem8="
script: php test/all.php
